name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

      - name: Build Unsigned Release APK
        run: ./gradlew assembleRelease --stacktrace
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: List APK files
        run: ls -la app/build/outputs/apk/release/
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Upload Unsigned Release APK
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 7
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
